name: Generate Snake Game Commits
on: 
  # run on every push on the master branch
  push:
    branches:
    - main
  
  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch snake-output
        uses: actions/checkout@v3
        with: 
          ref: 'snakegame-output'

      - name: generate
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}

          # list of files to generate.
          # one file per line. Each output can be customized with options as query string.
          #
          #  supported options:
          #  - palette:     A preset of color, one of [github, github-dark, github-light]
          #  - color_snake: Color of the snake
          #  - color_dots:  Coma separated list of dots color.
          #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
          #                 Exactly 5 colors are expected.
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark
          # dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: push generated snake game output
        run: |
          cp dist/github-snake-dark.svg ./
          git commit -am "snake game output"
          git push