name: Generate-Snake-Game
on: 
  # run on every push on the master branch
  push:
    branches:
    - main
  
  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  generate-and-replace-output:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch snake-output
        uses: actions/checkout@v3
        with: 
          ref: 'snakegame-output'
      
      - name: set git configs
        run: |
          git config user.name harrisadni
          git config user.email harris.dilham.adni@gmail.com

      - name: delete existing snake game output
        run: |
          rm assets/snakegame-output/github-snake-dark.svg
          git add .
          git commit -m "removing snake game output"
          git push

      - name: generate
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}

          # list of files to generate.
          # one file per line. Each output can be customized with options as query string.
          #
          #  supported options:
          #  - palette:     A preset of color, one of [github, github-dark, github-light]
          #  - color_snake: Color of the snake
          #  - color_dots:  Coma separated list of dots color.
          #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
          #                 Exactly 5 colors are expected.
          outputs: |
            assets/snakegame-output/github-snake-dark.svg?palette=github-dark
          # dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        
      - name: push current generated snake game output
        run: |
          git add assets/snakegame-output/github-snake-dark.svg
          git commit -m "adding current snake game output"
          git push